### ISSUE TITLE
Missing input files

### ISSUE THREAD

**Issue by kjetilk** [UW-Macrostrat/stromatolites_demo#2]
Hi!

I just ran the setup, but it failed to find some files, here's what I did:
```
kjetil@robin:~/dev/stromatolites_demo$ ./setup/setup.sh 
NOTICE:  table "strom_sentences_nlp" does not exist, skipping
DROP TABLE
CREATE TABLE
ERROR:  could not open file "/home/kjetil/dev/stromatolites_demo/input/sentences_nlp" for reading: No such file or directory
NOTICE:  table "strom_sentences_nlp352" does not exist, skipping
DROP TABLE
CREATE TABLE
CREATE INDEX
CREATE INDEX
COPY 14560
NOTICE:  table "strom_sentences_nlp352_bazaar" does not exist, skipping
DROP TABLE
CREATE TABLE
ERROR:  could not open file "/home/kjetil/dev/stromatolites_demo/input/sentences_nlp352_bazaar" for reading: No such file or directory
```

It seems to me that the only actual problems here are that the two files are missing, and indeed, I can't find them here on Github either.

**Comment by jonhusson** [comment]
Hi Kjeti,

That setup script is not well documented - sorry for the confusion. It actually just needs one of three potential inputs to work - in this case, the one that is included (strom_sentences_nlp352) was found and successfully ingested into psql. This table is what the app runs on, so you should be good to go, despite the thrown errors.

cheers,

jon

**Comment by kjetilk** [comment]
Oh, OK! I'll try to see if I can find some time to give it a spin! 

Cheers,

Kjetil
